# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_setdiff <- function(x, y) {
    .Call(`_finimom_arma_setdiff`, x, y)
}

subset_vector <- function(x, pos) {
    .Call(`_finimom_subset_vector`, x, pos)
}

set_vector_vals <- function(x, pos, vals) {
    .Call(`_finimom_set_vector_vals`, x, pos, vals)
}

LMarlik <- function(beta, sematinv, tau, psi, r, d, LDmat, gval) {
    .Call(`_finimom_LMarlik`, beta, sematinv, tau, psi, r, d, LDmat, gval)
}

LMarlikApprox <- function(beta, sematinv, z, tau, psi, r, d, LDmat, gval) {
    .Call(`_finimom_LMarlikApprox`, beta, sematinv, z, tau, psi, r, d, LDmat, gval)
}

gf <- function(x, z, sematinv, LDmat, tau, k, r) {
    .Call(`_finimom_gf`, x, z, sematinv, LDmat, tau, k, r)
}

opt_nm <- function(initval, pars) {
    .Call(`_finimom_opt_nm`, initval, pars)
}

posterior <- function(dat, tau, maxsize, r, p, niter, lpriorval, approx) {
    .Call(`_finimom_posterior`, dat, tau, maxsize, r, p, niter, lpriorval, approx)
}

